// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "myImage":return img`
..................................................
..................................................
..................................................
........................2.........................
........................2.........................
......................22222.......................
...................222.....222....................
.................22...........22..................
................2......222......2.................
..................222222.222222...................
................2......222......2.................
.................22...........22..................
...................222.....222....................
......................22222.......................
..................................................
................ffffffffffffffffff................
..............ff..................ff..............
.............f......................f.............
............f........................f............
............f........................f............
...........f....ffffffffffffffffff....f...........
...........f....fff.f.f.ff.f.f.fff....f...........
....5...5..f....f.ff.f.f..f.f.ff.f....f..a...a....
...5.....5.f....ff.ff.ffffff.ff.ff....f.a.....a...
...5.....5......f.f.fff....fff.f.f......a.....a...
...5.....5......ff.f..f....f..f.ff......a.....a...
...5.....5......f.f.fff....fff.f.f......a.....a...
...5.....5.f....ff.ff.ffffff.ff.ff....f.a.....a...
....5...5..f....f.ff.f.f..f.f.ff.f....f..a...a....
...........f....fff.f.f.ff.f.f.fff....f...........
...........f....ffffffffffffffffff....f...........
............f........................f............
............f........................f............
.............f......................f.............
..............ff..................ff..............
................ffffffffffffffffff................
..................................................
......................77777.......................
...................777.....777....................
.................77...........77..................
................7...............7.................
..................................................
................7...............7.................
.................77...........77..................
...................777.....777....................
......................77777.......................
........................7.........................
........................7.........................
..................................................
..................................................
`;
            case "image2":
            case "myImage0":return img`
..................................................
..................................................
..................................................
........................2.........................
........................2.........................
......................22222.......................
...................222.....222....................
.................22...........22..................
................2...............2.................
..................................................
................2...............2.................
.................22...........22..................
...................222.....222....................
......................22222.......................
..................................................
................ffffffffffffffffff................
..............ff..................ff..............
.............f......................f.............
............f........................f............
............f........................f............
...........f....ffffffffffffffffff....f...........
...........f....fff.f.f.ff.f.f.fff....f...........
....5...5..f....f.ff.f.f..f.f.ff.f....f..a...a....
...5.....5.f....ff.ff.ffffff.ff.ff....f.a.....a...
...5.....5......f.f.fff....fff.f.f......a.....a...
...5.....5......ff.f..f....f..f.ff......a.....a...
...5.....5......f.f.fff....fff.f.f......a.....a...
...5.....5.f....ff.ff.ffffff.ff.ff....f.a.....a...
....5...5..f....f.ff.f.f..f.f.ff.f....f..a...a....
...........f....fff.f.f.ff.f.f.fff....f...........
...........f....ffffffffffffffffff....f...........
............f........................f............
............f........................f............
.............f......................f.............
..............ff..................ff..............
................ffffffffffffffffff................
..................................................
......................77777.......................
...................777.....777....................
.................77...........77..................
................7......777......7.................
..................777777.777777...................
................7......777......7.................
.................77...........77..................
...................777.....777....................
......................77777.......................
........................7.........................
........................7.........................
..................................................
..................................................
`;
            case "image3":
            case "myImage1":return img`
..................................................
..................................................
..................................................
........................2.........................
........................2.........................
......................22222.......................
...................222.....222....................
.................22...........22..................
................2......222......2.................
..................222222.222222...................
................2......222......2.................
.................22...........22..................
...................222.....222....................
......................22222.......................
..................................................
................ffffffffffffffffff................
..............ff..................ff..............
.............f......................f.............
............f........................f............
............f........................f............
...........f....ffffffffffffffffff....f...........
...........f....ffffffffffffffffff....f...........
....5...5..f....f.ffffffffffffff.f....f..a...a....
...5.....5.f....ff.ffffffffffff.ff....f.a.....a...
...5.....5......f.f.fff....fff.f.f......a.....a...
...5.....5......ff.f..f....f..f.ff......a.....a...
...5.....5......f.f.fff....fff.f.f......a.....a...
...5.....5.f....ff.ffffffffffff.ff....f.a.....a...
....5...5..f....f.ffffffffffffff.f....f..a...a....
...........f....ffffffffffffffffff....f...........
...........f....ffffffffffffffffff....f...........
............f........................f............
............f........................f............
.............f......................f.............
..............ff..................ff..............
................ffffffffffffffffff................
..................................................
......................77777.......................
...................777.....777....................
.................77...........77..................
................7......777......7.................
..................777777.777777...................
................7......777......7.................
.................77...........77..................
...................777.....777....................
......................77777.......................
........................7.........................
........................7.........................
..................................................
..................................................
`;
            case "image4":
            case "myImage2":return img`
..................................................
..................................................
..................................................
........................2.........................
........................2.........................
......................22222.......................
...................222.....222....................
.................22...........22..................
................2......222......2.................
..................222222.222222...................
................2......222......2.................
.................22...........22..................
...................222.....222....................
......................22222.......................
..................................................
................ffffffffffffffffff................
..............ff..................ff..............
.............f......................f.............
............f........................f............
............f........................f............
...........f....ffffffffffffffffff....f...........
...........f....ffffffffffffffffff....f...........
....5...5..f....f.ffffffffffffff.f....f..a...a....
...5.....5.f....ff.ffffffffffff.ff....f.a.....a...
...5.....5......f.f.fff....fff.f.f......a.aaa.a...
...5.....5......ff.f..f....f..f.ff......a.a.a.a...
...5.....5......f.f.fff....fff.f.f......a.aaa.a...
...5.....5.f....ff.ffffffffffff.ff....f.a.....a...
....5...5..f....f.ffffffffffffff.f....f..a...a....
...........f....ffffffffffffffffff....f...........
...........f....ffffffffffffffffff....f...........
............f........................f............
............f........................f............
.............f......................f.............
..............ff..................ff..............
................ffffffffffffffffff................
..................................................
......................77777.......................
...................777.....777....................
.................77...........77..................
................7......777......7.................
..................777777.777777...................
................7......777......7.................
.................77...........77..................
...................777.....777....................
......................77777.......................
........................7.........................
........................7.........................
..................................................
..................................................
`;
            case "image5":
            case "myImage3":return img`
..................................................
..................................................
..................................................
........................2.........................
........................2.........................
......................22222.......................
...................222.....222....................
.................22...........22..................
................2......222......2.................
..................222222.222222...................
................2......222......2.................
.................22...........22..................
...................222.....222....................
......................22222.......................
..................................................
................ffffffffffffffffff................
..............ff..................ff..............
.............f......................f.............
............f........................f............
............f........................f............
...........f....ffffffffffffffffff....f...........
...........f....ffffffffffffffffff....f...........
....5...5..f....f.ffffffffffffff.f....f..a...a....
...5.....5.f....ff.ffffffffffff.ff....f.a.....a...
...5.555.5......f.f.fff....fff.f.f......a.....a...
...5.5.5.5......ff.f..f....f..f.ff......a.....a...
...5.555.5......f.f.fff....fff.f.f......a.....a...
...5.....5.f....ff.ffffffffffff.ff....f.a.....a...
....5...5..f....f.ffffffffffffff.f....f..a...a....
...........f....ffffffffffffffffff....f...........
...........f....ffffffffffffffffff....f...........
............f........................f............
............f........................f............
.............f......................f.............
..............ff..................ff..............
................ffffffffffffffffff................
..................................................
......................77777.......................
...................777.....777....................
.................77...........77..................
................7......777......7.................
..................777777.777777...................
................7......777......7.................
.................77...........77..................
...................777.....777....................
......................77777.......................
........................7.........................
........................7.........................
..................................................
..................................................
`;
            case "image6":
            case "myImage4":return img`
..................................................
..................................................
..................................................
........................2.........................
........................2.........................
......................22222.......................
...................222.....222....................
.................22...........22..................
................2......222......2.................
..................222222.222222...................
................2......222......2.................
.................22...........22..................
...................222.....222....................
......................22222.......................
..................................................
................ffffffffffffffffff................
..............ff..................ff..............
.............f......................f.............
............f........................f............
............f........................f............
...........f....ffffffffffffffffff....f...........
...........f....ffffffffffffffffff....f...........
....5...5..f....ffffffffffffffffff....f..a...a....
...5.....5.f....ffffffffffffffffff....f.a.....a...
...5.555.5......fffffff....fffffff......a.aaa.a...
...5.5.5.5......fffffff....fffffff......a.a.a.a...
...5.555.5......fffffff....fffffff......a.aaa.a...
...5.....5.f....ffffffffffffffffff....f.a.....a...
....5...5..f....ffffffffffffffffff....f..a...a....
...........f....ffffffffffffffffff....f...........
...........f....ffffffffffffffffff....f...........
............f........................f............
............f........................f............
.............f......................f.............
..............ff..................ff..............
................ffffffffffffffffff................
..................................................
......................77777.......................
...................777.....777....................
.................77...........77..................
................7......777......7.................
..................777777.777777...................
................7......777......7.................
.................77...........77..................
...................777.....777....................
......................77777.......................
........................7.........................
........................7.........................
..................................................
..................................................
`;
            case "image7":
            case "myImage5":return img`
..................................................
..................................................
..................................................
........................f.........................
........................f.........................
......................fffff.......................
...................fff.....fff....................
.................ff...........ff..................
................f......fff......f.................
..................ffffff.ffffff...................
................f......fff......f.................
.................ff...........ff..................
...................fff.....fff....................
......................fffff.......................
..................................................
................ffffffffffffffffff................
..............ff..................ff..............
.............f......................f.............
............f........................f............
............f........................f............
...........f....ffffffffffffffffff....f...........
...........f....f.f.f........f.f.f....f...........
....f...f..f....f.f.f........f.f.f....f..f...f....
...f.....f.f....f.f.f.ffffff.f.f.f....f.f.....f...
...f.fff.f......f.f.f.f....f.f.f.f......f.fff.f...
...f.f.f.f......f.f.f.f....f.f.f.f......f.f.f.f...
...f.fff.f......f.f.f.f....f.f.f.f......f.fff.f...
...f.....f.f....f.f.f.ffffff.f.f.f....f.f.....f...
....f...f..f....f.f.f........f.f.f....f..f...f....
...........f....f.f.f........f.f.f....f...........
...........f....ffffffffffffffffff....f...........
............f........................f............
............f........................f............
.............f......................f.............
..............ff..................ff..............
................ffffffffffffffffff................
..................................................
......................fffff.......................
...................fff.....fff....................
.................ff...........ff..................
................f......fff......f.................
..................ffffff.ffffff...................
................f......fff......f.................
.................ff...........ff..................
...................fff.....fff....................
......................fffff.......................
........................f.........................
........................f.........................
..................................................
..................................................
`;
            case "image9":
            case "myImage6":return img`
2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 
2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 
2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 
2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 
2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 
2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 
2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 
2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 
2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 
2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 
2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 
2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 
2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 
2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 
2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 
2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 
`;
            case "image10":
            case "myImage7":return img`
7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 
7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 
7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 
7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 
7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 
7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 
7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 
7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 
7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 
7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 
7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 
7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 
7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 
7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 
7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 
7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 
`;
            case "image11":
            case "myImage8":return img`
8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 
8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 
8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 
8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 
8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 
8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 
8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 
8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 
8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 
8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 
8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 
8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 
8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 
8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 
8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 
8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 
`;
            case "image12":
            case "myImage9":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . f f . . . . . . . . 
. . . . . f . f . . . . . . . . 
. . . . f . . f . . . . . . . . 
. . . f . . . f . . . . . . . . 
. . . . . . . f . . . . . . . . 
. . . . . . . f . . . . . . . . 
. . . . . . . f . . . . . . . . 
. . . . . . . f . . . . . . . . 
. . . . . . . f . . . . . . . . 
. . . . . . . f . . . . . . . . 
. . . . . . . f . . . . . . . . 
. . . f f f f f f f f f . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image13":
            case "myImage10":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . f f f f . . . . . . . 
. . . f f f . . f f . . . . . . 
. . f f . . . . . . f . . . . . 
. . . . . . . . . . f . . . . . 
. . . . . . . . . . f . . . . . 
. . . . . . . . . . f . . . . . 
. . . . . . . . . f f . . . . . 
. . . . . . . . f f . . . . . . 
. . . . . . f f f . . . . . . . 
. . . . . f f . . . . . . . . . 
. . . . . f . . . . f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image14":
            case "myImage11":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . f f f f f f . . . . . . 
. . . . . . . . . f . . . . . . 
. . . . . . . . . f . . . . . . 
. . . . . . . f f f . . . . . . 
. . . . . f f f . . . . . . . . 
. . . . . . . f f . . . . . . . 
. . . . . . . . . f . . . . . . 
. . . f . . . . . f . . . . . . 
. . . . f f f f f f . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image15":
            case "myImage12":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . f . . . . . . . . . . . . . 
. . f . . . . . . f . . . . . . 
. . f f . . . . . f f . . . . . 
. . . f . . . . . . f . . . . . 
. . . f . . . . . . f . . . . . 
. . . f . . . . . . f . . . . . 
. . . f . . . . . . f . . . . . 
. . . f f f f f f f f . . . . . 
. . . . . . . . . . f . . . . . 
. . . . . . . . . . f . . . . . 
. . . . . . . . . . f . . . . . 
. . . . . . . . . . f . . . . . 
. . . . . . . . . . f . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image16":
            case "myImage13":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . f f f f f f f f . . . . 
. . . . f . . . . . . . . . . . 
. . . . f . . . . . . . . . . . 
. . . . f . . . . . . . . . . . 
. . . . f . . . . . . . . . . . 
. . . . f . . . . . . . . . . . 
. . . . f f f f f f f f . . . . 
. . . . . . . . . . . f . . . . 
. . . . . . . . . . . f . . . . 
. . . . . . . . . . . f . . . . 
. . . . . . . . . . f f . . . . 
. . . . f f f f . . f . . . . . 
. . . . f . . f f f f . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image17":
            case "myImage14":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . f f . . . . . 
. . . . . . . f f . . . . . . . 
. . . . . . . f . . . . . . . . 
. . . . . . f . . . . . . . . . 
. . . . . . f . . . . . . . . . 
. . . . . f . . . . . . . . . . 
. . . . . f f f f f f . . . . . 
. . . . f . . . . . f f . . . . 
. . . . f . . . . . . f . . . . 
. . . f f . . . . . . f . . . . 
. . . f . . . . . . . f . . . . 
. . . f . . . . . . . f . . . . 
. . . . f f . . . f f f . . . . 
. . . . . . f f f f . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image18":
            case "myImage15":return img`
. . . . . . . . . . . . . . . . 
. . . f f f f f f f . . . . . . 
. . . f . . . . . f f f . . . . 
. . . . . . . . . . f f . . . . 
. . . . . . . . . f f . . . . . 
. . . . . . . . . f . . . . . . 
. . . . . . . . f . . . . . . . 
. . . . . . . f f . . . . . . . 
. . . . . . . f . . . . . . . . 
. . . . . . f f . . . . . . . . 
. . . . . f f . . . . . . . . . 
. . . . . f . . . . . . . . . . 
. . . . f f . . . . . . . . . . 
. . . . f . . . . . . . . . . . 
. . . f f . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image19":
            case "myImage16":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . f f . . . . . . 
. . . . . . f f . f f f . . . . 
. . . . . . f . . . . f . . . . 
. . . . . . f f . . . f . . . . 
. . . . . . . f f . . f . . . . 
. . . . . . . . f f f f . . . . 
. . . . . . . . . f f . . . . . 
. . . . . . . . . f f f . . . . 
. . . . . . . . f f . f . . . . 
. . . . . . . f f . . f . . . . 
. . . . . . f f . . . f . . . . 
. . . . . . f f . . f f . . . . 
. . . . . . . f f f f . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image20":
            case "myImage17":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . f f f f f f . . . . 
. . . . . f f . . . . f . . . . 
. . . . . f . . . . . f . . . . 
. . . . . f . . . . . f . . . . 
. . . . . f . . . . f f . . . . 
. . . . . f f . . . f . . . . . 
. . . . . . f f . . f . . . . . 
. . . . . . . f f f f . . . . . 
. . . . . . . . . f . . . . . . 
. . . . . . . . . f . . . . . . 
. . . . . . . . . f . . . . . . 
. . . . . . . . f . . . . . . . 
. . . . . . . f f . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image8":
            case "autumn":return img`
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ff888888888fffffffffffffff8888ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ff8888888888fffffffffffff8888888fffffff8888fffff888fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ff88888888888fffffffffff88888888fffffff8888fffff888ffffff88888888888888fffffffff222222fffffffffffff2222ffffffffff22222222222ffffffffff2222ffffffffffffffffffffff
ff888fff8888888ffffffff8888888888ffffff88888ffff888ffffff88888888888888fffffffff2222222222222fffff2222222ffffffff222222222222ffffff2222222ffffffffffffffffffffff
ff888fffff88888fffffff88888ff88888fffff888888fff888ffffff88888888888888fffffffff2222222222222ffff222222222fffffff2222222222222ffff22222222fff2222222ffffffffffff
ff8888fffff88888ffffff88888fff8888fffff888888fff888ffffffffffff888ffffffffffffff2222222222222fff22222222222ffffff222ffffff22222ff2222222fffff2222222ffff222fffff
ff8888ffffff8888ffffff8888ffff88888ffff8888888ff8888fffffffffff888ffffffffffffff2222ffffffffffff2222fff22222fffff222fffffff2222f222222fffffff2222222ffff22222222
fff888ffffff8888ffffff888ffffff8888ffff8888888ff8888fffffffffff888ffffffffffffff2222ffffffffffff2222ffff22222ffff222fffffff2222f22222ffffffff2222fffffff22222222
fff888fffffff8888fffff888fffffff888ffff88888888f8888fffffffffff888fffffffffffffff222ffffffffffff222ffffff2222ffff222ffffff222222222ffffffffff2222fffffff22222222
fff8888ffffff8888fffff888fffffff888ffff88888888ff888fffffffffff888fffffffffffffff222ffffffffffff222ffffff2222ffff222fff222222222222fffffffffff222ffffffffff222ff
fff8888fffffff888fffff888fffffff888fffff888f8888f888fffffffffff8888ffffffffffffff22222222fffffff222fffffff222ffff2222222222222f222ffffffffffff222ffffffffff222ff
ffff888fffffff888fffff888fffffff888fffff888f8888f888fffffffffff8888ffffffffffffff22222222222ffff222fffffff2222fff222222222222ff222ffffffffffff222ffffffffff222ff
ffff888ffffff8888fffff888fffffff888fffff888ff8888888fffffffffff8888ffffffffffffff22222222222fff2222fffffff2222ff2222222222fffff222ffffffffffff2222222ffffff222ff
ffff888ffffff8888fffff888fffffff888fffff888ff8888888ffffffffffff888ffffffffffffff222ff222222fff2222fffffff2222ff22222222fffffff222ffffffffffff2222222ffffff222ff
ffff888fffff8888ffffff888fffffff888fffff888fff888888ffffffffffff888ffffffffffffff222fffffffffff222ffffffff2222ff2222222222fffff222fff222222fff2222222ffffff222ff
ffff888fffff8888ffffff888ffffff8888fffff888fff8888888fffffffffff888ffffffffffffff222fffffffffff222ffffffff222fff222222222222fff222fff22222222f222ffffffffff222ff
ffff888ffff88888ffffff8888fffff8888fffff888ffff888888fffffffffff888fffffffffffff2222fffffffffff222ffffffff222fff2222ff2222222ff2222ff22222222f222ffffffffff222ff
ffff888ff888888fffffff8888ffff8888ffffff888fffff88888fffffffffff888fffffffffffff2222fffffffffff222fffffff2222fff2222fff2222222f2222ffffff2222f222ffffffffff222ff
ffff8888888888ffffffff888888888888ffffff8888ffff88888fffffffffff888fffffffffffff222ffffffffffff2222ffffff2222fff2222fffff222222f222fffff2222ff222ffffffffff222ff
ffff888888888ffffffffff8888888888fffffff8888fffff8888fffffffffff888fffffffffffff222ffffffffffff22222ffff2222fffff222ffffff22222f2222fff22222ff222ffffffffff222ff
ffff88888888ffffffffffff888888888ffffffff888fffff8888fffffffffff888fffffffffffff222fffffffffffff222222222222fffff222ffffffff222f2222ff22222fff222ffffffffff222ff
fffff888888fffffffffffffffffffffffffffffffffffffff888fffffffffff888fffffffffffff222fffffffffffff22222222222ffffff222ffffffffffff2222222222ffff222ffffffffff222ff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff22222222fffffff222fffffffffffff222222222ffff222fff222ffff222ff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff22222ffffffff222fffffffffffff22222222fffff222222222ffff222ff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff222222ffffff222222222ffff222ff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff2222fffffff22222222fffff222ff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffff11fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffff111111fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fff111ffff1fffffffff11111fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fff1ffffff11fffffff11fff111fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffff1ffffff1ffffff1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff222222ffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffff1ffffff1ffffff1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff2ffff2ffffffffff2fffff777777ffffffffffffffffffffffffffffffff
ffff1ffffff1ffffff1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff2ffff2ffffffffff2fffff7fffffffffffffffffffffffffffffffffffff
ffff1ffffff1ffffff1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff22222fff2222ffff2fffff7fffffffffffffffffffffffffffffffffffff
ffff1ffffff1ffffff11ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff2222ffff2222ff222fffff7fff77fffffff7777ff7777ff7777fffffffff
ffff11111111fffffff11111ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff2fff222f2fffff2f2ffffff7fff7ff7f77f7ff7ff7ff7ff7ff7fffffffff
fffffffffff1fffffffffff11fffffffff1ffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1ffffff2fffff2f2fffff2f2ffffff7fff7fff7fff7777ff7777ff7ff7fffffffff
fffffffffff1ffffffffffff11ffff111111fffffffffffffffffff11ffffffffffffffffffffffffffffffffffff1ffffffffffffff22222f222ffffff7fff7fff7ffff7ffff7fffff7ff7fffffffff
fffffffffff1fffffffffffff1ffff1ffff1fff1ffff1ff1111fff1111111ffff111ffff11ffffff111111111111111fffffffffffffffffffff2ffffff77777fff7ffff777ff7777ff7ff7fffffffff
fffffffffff1ffffff1ffffff1ffff1ffff1fff1ffff1f11ff1fff11fffffff11fff1ff1ff11ffffffffffffffffff11ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffff1ffffff1ffffff1ffff111111fff1ffff1f1fff11ff11ffffff11ff111ff11fffffffffffffffffff111fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffff1fffffff1fffff1fffffffff1fff1fff1ff1ff111ff1fffffff11111ffffff1ffffffffffffffffff1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffff11ffffff1111111fffffffff1ffff1111ff1111f11f1fffffff1fffffffffff1ffffffffffffffffffffffffffffffffffffffffff888fff8ffffffffffffffffffffffffffffffffffff
ffffffffffff1ffffffffffffffffffffff1ffffffffffff11ff1fffffffff111f11ff11ff1ffffffffffffffffffffffffffffff1111f1ffffff8ff88ff8fffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffff1fffffffffffffffffffffffffffff1fffff1111ffffffffffffffffffffffffffffff1ff1f111fff88fff8ff8fffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffff1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1ff1f1fffff8fff8fff8fffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffff11ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1111f1fffff88888fff8ffffffffff88fffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffff1ff1ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff8ff8fff88ff8fff8ff8ff8ffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffff111ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff8ff88ff8fff8ff88f8ff88ffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffff11ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff8ff88ff8fff8f88ff8f88fffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff888fff88ff888fff88fffffffffffffffffffffffff
fffff111ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff88888fffffffffffffffffffff
fffff1ff11ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffff1ffff11ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffff1fffff1ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffff1fffff1fffffffffffffffffffffffffffffffffffffffffff1ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffff1111111fffffffffffffffffffffffffffffffffffffffffff1fffffffffffffffffffffffff11111ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffff1f11ffffff1111fffffffffffffffffffffffffffffffffffff1ffffffffffffffffffffffff1fff11fffffffffffffffffffff1fffffffffffffffffffffffffffffffffffffffffffffffffff
fffff1ff11ffff11ff1ff1111ffffffffffff111ffffffffffffffff1fffffffffffffffffffffffffffff1fffffffffffffffffffff1ffffff1ffffffffffffffffffffffffffffffffffffffffffff
fffff11ff11fff11111ff11ff111111ffffff1f11f11ffffffffffff1fffff1111ffffffffffffffffffff1fffffffffffffffffffff1fffff11ffffffffffffffffffffffffffffffffffffffffffff
fffff11fff11ff11fffff1ffff11fff11fff1111ff111111f1ffffff11111f1ff1ff11111ffffffffff1111fffffffffffffff1fffff1fffff1fffffffffffffffffffffffffffffffffffffffffffff
fffff1fffff1fff11ffff1fffff1ffff1ff1ffffff1ffff11f11ffff1fff1f1111ff1fffffffffffffff1ffffff111111fffff11ffff1ff1ff1fffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffff11fff1fffff1ffff1f1ffff1ff1ffff1ffff1fff1fff1f1fffff1ffffffffffffffff1fffffffffff1111111fffff1f11f1ff1ff1111ffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffff11111fff1ffff1ffff11ff1ff11f1fffff1fffffffffff1ffff1ffffffffffffffff11fffff1f11f1ff1ff1ff1ffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffff1ff1111fff11111ffffffffffff11ff11ffffffffffffffff1ffffff111f11ff1ff1ff1ffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1111fffffffffffffffff1ffffff11ff11ff1ff1ff1ffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff11ff1ffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffff111fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffff1111ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffff11111ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffff111111fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffff111111fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffff11111111ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffff11111111ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffff111ff111ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffff1111ff1111fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffff1111ff1111fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffff1111fff1111ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffff111ffff1111ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffff111fffff111ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffff111fffff1111fffffffffffffffffffffffffffffffffffffffffffffffffffffff111fffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffff111fffff1111fffffffffffffffffffffffffffffffffffffffffffffffffffffff1111ffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffff1111ffffff111fffffffffffffffffffffffffffffffffffffffffffffffffffffff11111fffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffff1111ffffff111ffffffffffffffffffffffffffffffffffffffffffffffffffffffff11111ffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffff111fffffff1111fffffffff111111111fffffffffffffffffffffffffffffffffffff11111ffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffff111ff111111111fffffffff1111111111111111111111111111111111111111111111111111fffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffff111111111111111fffffffff1111111111111111111111111111111111111111111111111111fffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffff1111111111111111fffffffffffffff111111111111111111111111111111111111111111111fffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffff11111111ffff1111fffffffffffffffffffffffffffffffffffffffffffffffffffffff11111fffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffff1111ffffffffff1111ffffffffffffffffffffffffffffffffffffffffffffffffffffff11111fffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffff1111ffffffffff1111fffffffffffffffffffffffffffffffffffffffffffffffffffff111111fffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffff111fffffffffff1111ffffffffffffffffffffffffffffffffffffffffffffffffffff111111ffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffff1111ffffffffffff111fffffffffffffffffffffffffffffffffffffffffffffffffff11111ffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffff1111ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff11111ffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffff111fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff111ffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffff111ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
`;
            case "image21":
            case "autumn0":return img`
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
